# on:
#   schedule:
#     - cron: '*/6 * * * *'

# jobs:
#   test_schedule:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Probando
#         run: for ((i=1; i<=600; i++)); do; echo $i; sleep 1; done;


on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Loop through numbers
        id: loop
        run: |
          for ((i=1; i<=600; i++))
          do
            echo "Current number: $i"
            sleep 1
          done
